# -*- coding: utf-8 -*-
"""hw06_consumer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEUVfiodyffwqtGJytLzS2qslUMy4x41
"""

!pip install pyspark

from pyspark.sql import SparkSession
  
spark = SparkSession.builder.appName("DataFrame").getOrCreate()
sc = spark.sparkContext

df = spark.read.load("stream.txt", format="json")

df.collect()

latitudes = []
longitudes = []
for itertator in df.collect():
  latitudes.append(itertator["iss_position"][0])
  longitudes.append(itertator["iss_position"][1])

import pandas as pd
d = {'longitude':longitudes,'latitude':latitudes}
pd_df = pd.DataFrame(d)

pd_df = pd_df.astype('float')

import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme()
sns.relplot(data=pd_df, x="longitude", y="latitude").set(title='Longitude and Latitude of the ISS')
plt.suptitle("taken from 1648833856\n to 1648837448")
plt.show()

