# -*- coding: utf-8 -*-
"""hw06_consumer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEUVfiodyffwqtGJytLzS2qslUMy4x41
"""

!pip install pyspark

from pyspark.sql import SparkSession
  
spark = SparkSession.builder.appName("DataFrame").getOrCreate()
sc = spark.sparkContext

df = spark.read.load("stream.txt", format="json")

df.collect()

latitudes = []
longitudes = []
for itertator in df.collect():
  latitudes.append(float(itertator["iss_position"][0]))
  longitudes.append(float(itertator["iss_position"][1]))

import pandas as pd
d = {'longitude':longitudes,'latitude':latitudes}
pd_df = pd.DataFrame(d)

pd_df = pd_df.astype('float')

longmin = min(longitudes)
latmin = min(latitudes)
longmax = max(longitudes)
latmax = max(latitudes)
print(longmin, longmax, latmin, latmax)

import matplotlib.pyplot as plt
from matplotlib import rcParams

img = plt.imread("worldmap.jpg")

longmin = min(longitudes)
latmin = min(latitudes)
longmax = max(longitudes)
latmax = max(latitudes)

# figure size in inches
plt.scatter(data=pd_df, x="longitude", y="latitude", zorder = 1)
plt.imshow(img, zorder=0, extent=[longmin, longmax, latmin, latmax])
plt.title('Longitude and Latitude of the ISS')
plt.suptitle("taken from Timestamp 1648833856\n to Timestamp 1648837448")
plt.show()
plt.savefig('hw06_map.jpg')

